### ISSUE TITLE
Some weird error

### ISSUE THREAD

**Issue by Safhyy** [RappyLabyAddons/LabyGPT#21] opened 2024-08-10 17:24 UTC
So I entered my api key and selected the free gpt version but it says "You exceeded your current quota, please check your plan and billing details. For more informations on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors".

**Comment by RappyTV** [comment] 2024-08-10 17:55
duplicate of #14

**Closed by RappyTV** 2024-08-10 17:55 UTC
Labels: duplicate
